/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.renewableenergy;

/**
 *
 * @author steph
 */
    public class EnergyCalculatorApp extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public EnergyCalculatorApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLEnergyUsePm = new javax.swing.JLabel();
        TFEnergyUsePm = new javax.swing.JTextField();
        LBLEnergyCostPm = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        TFEnergyCostPm = new javax.swing.JTextField();
        LBLSavings = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CBDetached = new javax.swing.JCheckBox();
        CBSemiDetatched = new javax.swing.JCheckBox();
        CBApartment = new javax.swing.JCheckBox();
        CBBungalow = new javax.swing.JCheckBox();
        LBLUnitsM3 = new javax.swing.JLabel();
        TFUnitsM3 = new javax.swing.JTextField();
        LBLConversionFactor = new javax.swing.JLabel();
        TFConversionFactor = new javax.swing.JTextField();
        LBLUnitPrice = new javax.swing.JLabel();
        TFUnitPrice = new javax.swing.JTextField();
        LBLCarbonTax = new javax.swing.JLabel();
        LBLStandingCharger = new javax.swing.JLabel();
        TFStandingCharge = new javax.swing.JTextField();
        TFCarbonTax = new javax.swing.JTextField();
        LBLEnergyType = new javax.swing.JLabel();
        CBSolar = new javax.swing.JCheckBox();
        CBWind = new javax.swing.JCheckBox();
        CBHydro = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));

        LBLEnergyUsePm.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        LBLEnergyUsePm.setText("Energy use per month (kwh) ");

        TFEnergyUsePm.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N

        LBLEnergyCostPm.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        LBLEnergyCostPm.setText("Energy expense per month (€) ");

        submitButton.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        TFEnergyCostPm.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N

        LBLSavings.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        LBLSavings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        resetButton.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        jLabel1.setText("Type of House");

        CBDetached.setText("Detatched");
        CBDetached.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDetachedActionPerformed(evt);
            }
        });

        CBSemiDetatched.setText("Semi-detatched");
        CBSemiDetatched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSemiDetatchedActionPerformed(evt);
            }
        });

        CBApartment.setText("Apartment");

        CBBungalow.setText("Bungalow");

        LBLUnitsM3.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        LBLUnitsM3.setText("Units (cubic meters e.g 264)");

        TFUnitsM3.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N

        LBLConversionFactor.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        LBLConversionFactor.setText("Conversion Factor (e.g 11.2285)");

        TFConversionFactor.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        TFConversionFactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFConversionFactorActionPerformed(evt);
            }
        });

        LBLUnitPrice.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        LBLUnitPrice.setText("Unit Price (€ e.g 0.04750)  ");

        TFUnitPrice.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N

        LBLCarbonTax.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        LBLCarbonTax.setText("Carbon Tax");

        LBLStandingCharger.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        LBLStandingCharger.setText("Standing charge");

        TFStandingCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFStandingChargeActionPerformed(evt);
            }
        });

        TFCarbonTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCarbonTaxActionPerformed(evt);
            }
        });

        LBLEnergyType.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        LBLEnergyType.setText("Choose applicible ");

        CBSolar.setText("Solar");
        CBSolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSolarActionPerformed(evt);
            }
        });

        CBWind.setText("Wind-Power");
        CBWind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBWindActionPerformed(evt);
            }
        });

        CBHydro.setText("Hydro-electric");
        CBHydro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBHydroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LBLSavings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFEnergyCostPm, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(TFEnergyUsePm)
                            .addComponent(LBLEnergyUsePm)
                            .addComponent(LBLEnergyCostPm)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CBSemiDetatched, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CBDetached, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CBBungalow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CBApartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLEnergyType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBLConversionFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBLUnitsM3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFUnitsM3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFConversionFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CBWind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CBSolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CBHydro, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBLUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LBLStandingCharger, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TFStandingCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LBLCarbonTax, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(TFCarbonTax)))
                    .addComponent(TFUnitPrice))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LBLUnitPrice, LBLUnitsM3});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TFConversionFactor, TFEnergyCostPm, TFEnergyUsePm, TFUnitsM3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLEnergyUsePm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLUnitsM3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLUnitPrice))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFEnergyUsePm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFUnitsM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLEnergyCostPm)
                    .addComponent(LBLConversionFactor)
                    .addComponent(LBLCarbonTax)
                    .addComponent(LBLStandingCharger))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFEnergyCostPm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFConversionFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFStandingCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFCarbonTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLEnergyType)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBDetached)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBSemiDetatched)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBApartment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBBungalow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBSolar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBWind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBHydro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(LBLSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(resetButton)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LBLUnitPrice, LBLUnitsM3});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TFCarbonTax, TFConversionFactor, TFStandingCharge});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        ElectricityConversion electricConvert = new ElectricityConversion();
        GasConversion gasConvert = new GasConversion
        ();

            try {
                double energyUsePm = Double.parseDouble(TFEnergyUsePm.getText());
                double energyCostPm = Double.parseDouble(TFEnergyCostPm.getText());
                double unitsM3 = Double.parseDouble(TFUnitsM3.getText());
                double conversionFactor = Double.parseDouble(TFConversionFactor.getText());
                double carbonTax = Double.parseDouble(TFCarbonTax.getText());
                double standingCharge = Double.parseDouble(TFStandingCharge.getText());
                

                electricConvert.setEnergyUsePm(energyUsePm);
                electricConvert.setEnergyRatePm(energyCostPm);
                gasConvert.setUnitsM3(unitsM3);
                gasConvert.setConversionFactor(conversionFactor);
                gasConvert.setCarbonTax(carbonTax);
                gasConvert.setStandingCharge(standingCharge);

                electricConvert.computeEnergyPrice();
                gasConvert.computeGasPrice();
                gasConvert.computeCharges();
                double clientElectricSave = electricConvert.computeSavings();
                LBLSavings.setText("Electricy Savings: " + clientElectricSave);
            } catch (NumberFormatException e) {
                // Handle the exception when input values are not valid numbers
                LBLSavings.setText("Invalid input. Please enter valid numeric values.");
            }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        TFEnergyUsePm.setText("");
        TFEnergyCostPm.setText("");
        LBLSavings.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void CBDetachedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDetachedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBDetachedActionPerformed

    private void CBSemiDetatchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSemiDetatchedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBSemiDetatchedActionPerformed

    private void TFConversionFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFConversionFactorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFConversionFactorActionPerformed

    private void TFStandingChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFStandingChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFStandingChargeActionPerformed

    private void TFCarbonTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCarbonTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCarbonTaxActionPerformed

    private void CBSolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSolarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBSolarActionPerformed

    private void CBWindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBWindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBWindActionPerformed

    private void CBHydroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBHydroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBHydroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnergyCalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnergyCalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnergyCalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnergyCalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnergyCalculatorApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBApartment;
    private javax.swing.JCheckBox CBBungalow;
    private javax.swing.JCheckBox CBDetached;
    private javax.swing.JCheckBox CBHydro;
    private javax.swing.JCheckBox CBSemiDetatched;
    private javax.swing.JCheckBox CBSolar;
    private javax.swing.JCheckBox CBWind;
    private javax.swing.JLabel LBLCarbonTax;
    private javax.swing.JLabel LBLConversionFactor;
    private javax.swing.JLabel LBLEnergyCostPm;
    private javax.swing.JLabel LBLEnergyType;
    private javax.swing.JLabel LBLEnergyUsePm;
    private javax.swing.JLabel LBLSavings;
    private javax.swing.JLabel LBLStandingCharger;
    private javax.swing.JLabel LBLUnitPrice;
    private javax.swing.JLabel LBLUnitsM3;
    private javax.swing.JTextField TFCarbonTax;
    private javax.swing.JTextField TFConversionFactor;
    private javax.swing.JTextField TFEnergyCostPm;
    private javax.swing.JTextField TFEnergyUsePm;
    private javax.swing.JTextField TFStandingCharge;
    private javax.swing.JTextField TFUnitPrice;
    private javax.swing.JTextField TFUnitsM3;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
